### ISSUE TITLE
Weird issue on how `line_comment` works

### ISSUE THREAD

**Issue by GrayJack** [Razzeee/tree-sitter-elm#24]
I'm creating a elm atom package using your library and a strange thing happened

I map `line_comments` as comments in the css class in atom, 
and this happens

![elm_treesitter](https://user-images.githubusercontent.com/17973728/66668932-c9cecc00-ec2c-11e9-9912-a298cb80279f.png)

Not sure why, since I could not find the source of `externals` in the source code

**Comment by Razzeee** [comment]
Relevant file is https://github.com/Razzeee/tree-sitter-elm/blob/master/src/scanner.cc

Can you please post the complete example code? I can look at it on monday

**Comment by GrayJack** [comment]
Sure, you can find it here: https://github.com/GrayJack/language-elm-treesitter/blob/master/grammars/tree-sitter-elm.cson#L32

**Comment by Razzeee** [comment]
https://github.com/Razzeee/tree-sitter-elm/pull/25 should fix this. It might also affect the `negate_expr`.

**Comment by GrayJack** [comment]
I think I never saw a negate expression, can you give me a example?

**Comment by Razzeee** [comment]
Well it's at least what we parse it as :)

https://github.com/Razzeee/tree-sitter-elm/blob/7821b8a941badf11cade7496c0acf41e03bfba8a/corpus/basic.txt#L99

**Comment by GrayJack** [comment]
Seems like it didn't fix, in my repo, I did use the new branch and still nothing

**Comment by Razzeee** [comment]
Did you actually rebuild it, via `npm run build`? I'm very confident, that the error you mentioned is fixed by this :)

**Comment by GrayJack** [comment]
Maybe I did forget, will double check as soon as I can, sorry for the trouble

**Comment by GrayJack** [comment]
Looks like the problem is that apm have to run that, but atom actually expects to be already done.
Can you help me out with this? Kinda lost, not very used with JS stuff, how ca I make my atom package run that before installing?

**Comment by Razzeee** [comment]
Should I just publish it on npm? Would that help?

**Comment by GrayJack** [comment]
I think it would

**Comment by Razzeee** [comment]
Pushed a new release to npm and new release builds should shortly show up on github.
Please let me know if it solved it :)

**Comment by GrayJack** [comment]
Worked just fine now
